# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Agama')),
                ('aktif', models.BooleanField(help_text='Centang jika ingin mengaktifkan', verbose_name='Ya/Tidak')),
            ],
            options={
                'db_table': 'agama',
                'verbose_name_plural': 'Agama',
            },
        ),
    ]
