# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_sekolah', '0003_jurusan_siswa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=5, verbose_name='Kelas')),
            ],
            options={
                'db_table': 'kelas',
                'verbose_name_plural': 'Kelas',
            },
        ),
        migrations.AlterField(
            model_name='siswa',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
