# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_sekolah', '0004_auto_20170829_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='jur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_sekolah.Jurusan'),
        ),
        migrations.AddField(
            model_name='siswa',
            name='kelas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_sekolah.Kelas'),
        ),
    ]
